---
# Main tasks file for fubarhouse.nodejs

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined and fubarhouse_user is undefined

- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined and fubarhouse_user is undefined

- name: "Define OS-specific variables"
  include_vars: "config-{{ ansible_os_family }}.yml"
  when: fubarhouse_npm is not defined

- include: nvm.yml
  when: install_nvm

- include: ivm.yml
  when:
    - install_ivm == true
    - '"{{ ansible_os_family }}" != "Darwin"'

- include: nodejs.yml
  when: install_nodejs == true

- include: iojs.yml
  when:
    - install_iojs == true
    - '"{{ ansible_os_family }}" != "Darwin"'

- include: npm.yml
  when: install_npm == true